#!/usr/bin/env bash
#Fixes a web server to run nginx as the nginx user listening to port 8080
sudo sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sudo sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sudo chmod 644 /etc/nginx/nginx.conf
sudo pkill apache2
sudo sudo -u nginx service nginx start
